macro(add_module MODULE)
  string(REPLACE "../" "" MODULE_BUILD ${MODULE})
  add_subdirectory(${MODULE} ${CMAKE_CURRENT_BINARY_DIR}/${MODULE_BUILD})
  get_property(CURRENT_MODULE_INCLUDES DIRECTORY ${MODULE} PROPERTY INCLUDE_DIRECTORIES)
  list(APPEND ALL_INCLUDES ${CURRENT_MODULE_INCLUDES})
endmacro()

macro(add_unused_includes_target)
  if (ALL_INCLUDES)
    list(REMOVE_DUPLICATES ALL_INCLUDES)
    foreach (dir ${ALL_INCLUDES})
      if ((NOT ${dir} MATCHES "^${CMAKE_CURRENT_LIST_DIR}/src") OR (NOT EXISTS ${dir}))
        list(REMOVE_ITEM ALL_INCLUDES ${dir})
        if (NOT EXISTS ${dir})
          message(WARNING "Directory '${dir}' was included but does not exist. Please fix the corresponding CMakeLists.txt")
        endif ()
      endif ()
    endforeach ()
    add_library(enable_include_folders ${ALL_INCLUDES} .enable_include_folders.cpp)
  endif ()
endmacro()
